# Generated by Django 4.1.5 on 2023-02-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cosechacampo',
            old_name='idDanos',
            new_name='iddanos',
        ),
    ]
