# Generated by Django 4.1.5 on 2023-02-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaC', '0002_rename_iddanos_cosechacampo_iddanos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosechacampo',
            name='iddanos',
        ),
    ]
